version: '3.2'
services:
  geth:
    image: "matterlabs/geth:latest"
    logging:
        driver: none 
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - type: bind
        source: ./volumes/geth
        target: /var/lib/geth/data
  postgres:
    image: "postgres:12"
    logging:
      driver: none 
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./volumes/postgres
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  zksync:
    stdin_open: true
    tty: true
    image: matterlabs/local-node:latest2.0
    depends_on:
      - geth
      - postgres
    ports:
      - "3050:3050" # JSON RPC HTTP port
      - "3051:3051" # JSON RPC WS port
    volumes:
      # Configs folder bind
      - type: bind
        source: ./volumes/zksync/env/dev
        target: /etc/env/dev
      # Storage folder bind
      - type: bind
        source: ./volumes/zksync/data
        target: /var/lib/zksync/data
    environment:
      - DATABASE_URL=postgres://postgres@postgres/zksync_local
      - ETH_CLIENT_WEB3_URL=http://geth:8545
